#!/usr/bin/env php
<?php

// 命令行程序开发环境入口文件

require __DIR__.'/bootstrap.php';

$config = [
    'id' => 'yii2-log-console-dev',
];

$config = \yii\helpers\ArrayHelper::merge(
    require __DIR__.'/config/common.php',
    require __DIR__.'/config/console.php',
    $config
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
