#!/usr/bin/env php
<?php

// 命令行程序测试环境入口文件

define('YII_ENV', 'test');
define('YII_DEBUG', true);

require __DIR__.'/bootstrap.php';

$config = [
    'id' => 'yii2-log-console-test',
    'components' => [
        'db' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host='.$_ENV['DB_TEST_HOST'].';dbname='.$_ENV['DB_TEST_DATABASE'],
            'username' => $_ENV['DB_TEST_USERNAME'],
            'password' => $_ENV['DB_TEST_PASSWORD'],
            'charset' => $_ENV['DB_CHARSET'],
        ],
    ],
];

$config = \yii\helpers\ArrayHelper::merge(
    require __DIR__.'/config/common.php',
    require __DIR__.'/config/console.php',
    $config
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
